import {re} from '@babel/core/lib/vendor/import-meta-resolve';

const Icons = {
  pitch: require('./pitch.png'),
  footballPhone: require('./footballPhone.png'),
  trophy: require('./trophy.png'),
  trophySmall: require('./trophySmall.png'),
  burger: require('./burger.png'),
  burgerSmall: require('./burgerSmall.png'),
  pokerChips: require('./pokerChips.png'),
  coins: require('./coins.png'),
  coinsSmall: require('./coinsSmall.png'),
  laur: require('./laur.png'),
  medal: require('./medal.png'),
  medalSmall: require('./medalSmall.png'),
  achievement: require('./achievement.png'),
  achievementSmall: require('./achievementSmall.png'),
  money: require('./money.png'),
  moneySmall: require('./moneySmall.png'),
  ranking: require('./ranking.png'),
  coupon: {
    won: require('./couponWon.png'),
    wonSmall: require('./couponWonSmall.png'),
    waiting: require('./couponWaiting.png'),
    waitingSmall: require('./couponWaitingSmall.png'),
    new: require('./couponNew.png'),
    newSmall: require('./couponNewSmall.png'),
    lost: require('./couponLost.png'),
    lostSmall: require('./couponLostSmall.png'),
  },
  bet: {
    wonFull: require('./betWonFull.png'),
    wonPart: require('./betWonPart.png'),
    lost: require('./betLost.png'),
  },
  expandArrow: require('./expandArrow.png'),
  match: {
    won: require('./ok.png'),
    wonSmall: require('./okSmall.png'),
    lost: require('./cancel.png'),
    lostSmall: require('./cancelSmall.png'),
    pending: require('./time.png'),
    pendingSmall: require('./timeSmall.png'),
    error: require('./error.png'),
    errorSmall: require('./errorSmall.png'),
  },
  rpg: {
    cash: require('./rpg/cash.png'),
    client: require('./rpg/client.png'),
    energy: require('./rpg/energy.png'),
    food: require('./rpg/food.png'),
    points: require('./rpg/points.png'),
    price: require('./rpg/price.png'),
    promotion: require('./rpg/promotion.png'),
    upgrades: require('./rpg/upgrades.png'),
    workers: require('./rpg/workers.png'),
  },
};

export default Icons;
